name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # DFX’in otomatik kurulacağı dizin
      DFX_HOME: $HOME/.local/share/dfx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache NPM modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers & deps
        run: |
          npx playwright install --with-deps
          sudo apt-get update
          sudo apt-get install -y libnspr4 libnss3 libasound2

      - name: Install DFX
        run: |
          curl -fsSL https://sdk.dfinity.org/install.sh | sh
      - name: Add DFX to PATH
        # Bütün sonraki adımlarda dfx bulunabilsin diye
        run: echo "PATH=\$HOME/.local/share/dfx/bin:\$PATH" >> $GITHUB_ENV

      - name: Verify dfx
        run: dfx --version

      - name: Start local IC replica
        run: dfx start --clean --background

      - name: Deploy canisters locally
        run: dfx deploy --no-wallet

      - name: Run Playwright tests
        run: npm test

      - name: Shutdown replica
        if: always()
        run: dfx stop
