name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: src/onescrt_frontend
        run: npm ci

      - name: Install Playwright dependencies
        working-directory: src/onescrt_frontend
        run: |
          npx playwright install
          npx playwright install-deps

      - name: Install DFX
        uses: dfinity/setup-dfx@main

      - name: Add DFX to PATH
        run: echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH

      - name: Start local IC replica
        run: dfx start --clean --background

      - name: Deploy canisters locally
        run: dfx deploy --network local --no-wallet --yes

      - name: Run Playwright tests
        working-directory: src/onescrt_frontend
        run: npm test

      - name: Stop replica
        if: always()
        run: dfx stop
