name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          # "auto" dfx.json'dan; istersen sabit sürüm yazabilirsin
          dfx-version: auto

      - name: Verify dfx
        run: dfx --version

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./src/onescrt_frontend

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Start local IC replica
        run: dfx start --clean --background

      - name: Deploy canisters locally
        run: |
          cd ~/onescrt
          dfx deploy --no-wallet --yes

      - name: Run Playwright tests
        run: npm test
        working-directory: ./src/onescrt_frontend

      - name: Shutdown replica
        if: always()
        run: dfx stop
