name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v18
        with:
          node-version: '18'

      - name: Install npm deps (frontend)
        working-directory: ./src/onescrt_frontend
        run: npm ci

      - name: Install Playwright browsers & deps
        working-directory: ./src/onescrt_frontend
        run: |
          npx playwright install-deps
          npx playwright install

      - name: Install DFX
        uses: dfinity/setup-dfx@v1
        with:
          version: v0.27.0
          modify-path: true

      - name: Verify dfx
        run: dfx --version

      - name: Start local IC replica
        run: dfx start --background --clean

      - name: Deploy canisters locally
        run: dfx deploy --network local --no-wallet --yes

      - name: Run Playwright tests
        working-directory: ./src/onescrt_frontend   # <-- Burayı ekledik
        run: npx playwright test

      - name: Stop replica
        run: dfx stop
