name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Kodunu çek
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Node.js kur (frontend için)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Frontend bağımlılıklarını yük
      - name: Install frontend dependencies
        working-directory: src/onescrt_frontend
        run: npm ci

      # 4) Playwright’ın sistem bağımlılıklarını yükle
      - name: Install Playwright deps
        run: npx playwright install-deps

      # 5) DFX’i kur
      - name: Install DFX
        uses: dfinity/setup-dfx@main

      # 6) DFX komutunu kullanabilmek için PATH’e ekle
      - name: Add DFX to PATH
        run: echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH

      # 7) Local IC (replica) başlat
      - name: Start local IC replica
        run: dfx start --background --clean

      # 8) Canister’ları ayağa kaldır (onay sormadan)
      - name: Deploy canisters locally
        run: dfx deploy --no-wallet --network local --yes

      # 9) Playwright testlerini çalıştır
      - name: Run Playwright tests
        run: npx playwright test

      # 10) Her durumda replica’yı kapat
      - name: Stop replica
        if: always()
        run: dfx stop
