name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: src/onescrt_frontend
        run: npm install

      - name: Install Playwright deps
        working-directory: src/onescrt_frontend
        run: |
          npx playwright install
          npx playwright install-deps

      - uses: dfinity/setup-dfx@main

      - name: Add DFX to PATH
        run: echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH

      - name: Start local IC replica
        run: dfx start --clean --background

      - name: Deploy canisters locally
        run: dfx deploy --network local --no-wallet --yes

      - name: Export FRONTEND_URL
        run: |
          ID=$(dfx canister id onescrt_frontend)
          echo "FRONTEND_URL=http://127.0.0.1:4943/?canisterId=$ID" >> $GITHUB_ENV

      - name: Run Playwright tests
        working-directory: src/onescrt_frontend
        run: npm test

      - if: always()
        name: Stop replica
        run: |
          if command -v dfx >/dev/null 2>&1; then
            dfx stop
          fi
